trigger:
  - main

pool :
 vmImage: ubuntu-latest

stages:
  - stage: terraforminstall
    displayName: 
    jobs:
      - job: terraforminit
        displayName: terraform
          - task :TerraformTask@5
           inputs :
            provider :'azurerm'
            command :'init'

        job :terraformplan
          - task :TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'

    -stage : 
     dispalyName : CodeScan
        
    -stage : manualValidation
